# Generated by Django 3.1.6 on 2021-06-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CriminalDataAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('dob', models.DateField()),
                ('known_crimes', models.TextField()),
                ('registered', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('registered_at', models.CharField(default='', max_length=100)),
                ('custody', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('latest_sightings_time', models.TimeField()),
                ('latest_sightings_date', models.DateField()),
                ('latest_sightings_place', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
