# Generated by Django 3.1.6 on 2021-06-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('subject', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
    ]
